
project_id = "oeepmsbttxfknkznbnym"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54326
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[functions.create-payos-payment]
verify_jwt = true

[functions.payos-webhook]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = true

[functions.check-expired-subscriptions]
verify_jwt = false

[functions.ai-chat-proxy]
verify_jwt = true

[functions.generate-sitemap]
verify_jwt = false

[functions.ping-google-sitemap]
verify_jwt = false

[functions.generate-sitemap-index]
verify_jwt = false

[functions.generate-sitemap-static]
verify_jwt = false

[functions.generate-sitemap-profiles]
verify_jwt = false

[functions.generate-sitemap-fake-profiles]
verify_jwt = false

[edge_runtime]
enabled = true
port = 54327

[analytics]
enabled = false
